services:
  - type: web
    name: fast-learning
    env: python
    region: oregon
    plan: free
    buildCommand: "pip install --upgrade pip && pip install -r requirements.txt"
    startCommand: "python backend/app.py"
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0
